#!/bin/bash

ROOT_DIR=`pwd`
TARGET="arm"
TARGET_HOST="arm-linux-androideabi"
ARM_PREFIX=$ROOT_DIR/arm
NDK_ROOT=$ROOT_DIR/cross
SYSROOT=$NDK_ROOT/sysroot
PATH=$NDK_ROOT/bin:$PATH
CXX="${TARGET_HOST}-g++"
CC="${TARGET_HOST}-gcc"
LD="${TARGET_HOST}-ld"

PBUF_URL="https://github.com/google/protobuf/archive/v3.1.0.tar.gz"
PBUF_DIR="protobuf"

if [[ ! -d $PBUF_DIR ]]; then
    printf "\n[*]Downloading $PBUF_DIR\n\n"
    curl -L $PBUF_URL > $PBUF_DIR.tar.gz
    mkdir $PBUF_DIR
    tar --strip=1 -xzvf $PBUF_DIR.tar.gz -C $PBUF_DIR 1>/dev/null
    cd $ROOT_DIR/$PBUF_DIR
    ./autogen.sh 1>/dev/null
    ./configure --prefix=$ARM_PREFIX \
        --host=arm-linux-androideabi \
        --with-protoc=/usr/bin/protoc \
        --disable-shared \
        --enable-static \
        LDFLAGS="-llog"
    printf "\n[*]Compiling $PBUF_DIR\n\n"
    make -j$(nproc)
    printf "\n[*]Installing $PBUF_DIR\n\n"
    make install
fi
