#!/bin/bash

source ./env_setup

PROTOBUFC_URL="https://github.com/protobuf-c/protobuf-c/archive/v1.3.0.tar.gz"

PBUFC_DIR="protobuf-c"

export PKG_CONFIG_PATH=$BUILD_DIR/lib/pkgconfig
if [[ ! -d $PBUFC_DIR ]]; then
    curl -L $PROTOBUFC_URL > $PBUFC_DIR.tar.gz
    mkdir $PBUFC_DIR
    tar --strip=1 -xzvf $PBUFC_DIR.tar.gz -C $PBUFC_DIR
    cd $ROOT/$PBUFC_DIR
    ./autogen.sh
    CPPFLAGS=`pkg-config --cflags protobuf` \
    LDFLAGS=`pkg-config --libs protobuf` \
    ./configure --prefix=$BUILD_DIR \
        --disable-shared --enable-static --disable-protoc \
        --host=$TARGET_HOST
    make -j$(nproc) && make install
fi
