#!/bin/bash

export ROOT=`pwd`

CRIU_URL="https://github.com/NoMore201/criu/archive/v3.5.tar.gz"

PBUF_DIR="protobuf"
PBUFC_DIR="protobuf-c"
CRIU_DIR="criu"
LIBNL_DIR="libnl"
LIBNET_DIR="libnet"
TARGET="arm"

export NDK_ROOT=$ROOT/cross
export BUILD_DIR=$ROOT/$TARGET
export SYSROOT=$NDK_ROOT/sysroot
export PATH=$NDK_ROOT/bin:$PATH
export CXX="arm-linux-androideabi-g++"
export CC="arm-linux-androideabi-gcc"

if [[ ! -d $CRIU_DIR ]]; then
    curl -L $CRIU_URL > $CRIU_DIR.tar.gz
    mkdir $CRIU_DIR
    tar --strip=1 -xzvf $CRIU_DIR.tar.gz -C $CRIU_DIR
fi

cd $ROOT/$CRIU_DIR
rm images/google/protobuf/descriptor.proto
cp $ROOT/descriptor.proto images/google/protobuf
make clean
make -j$(nproc) \
    ARCH=arm \
    CROSS_COMPILE=$NDK_ROOT/bin/arm-linux-androideabi- \
    USERCFLAGS="-I${BUILD_DIR}/include -L${BUILD_DIR}/lib" \
    PATH=/usr/local/bin:$PATH \
    criu

cd $ROOT
