#!/bin/bash

export ROOT=`pwd`

LIBNET_URL="https://github.com/sam-github/libnet/archive/libnet-1.2.tar.gz"

PBUF_DIR="protobuf"
PBUFC_DIR="protobuf-c"
CRIU_DIR="criu"
LIBNL_DIR="libnl"
LIBNET_DIR="libnet"
TARGET="arm"

export NDK_ROOT=$ROOT/cross
export BUILD_DIR=$ROOT/$TARGET
export SYSROOT=$NDK_ROOT/sysroot
export PATH=$NDK_ROOT/bin:$PATH
export CXX="arm-linux-androideabi-g++"
export CC="arm-linux-androideabi-gcc"

if [[ ! -d $LIBNET_DIR ]]; then
    printf "\n[*]Downloading $LIBNET_DIR\n\n"
    curl -L $LIBNET_URL > $LIBNET_DIR.tar.gz
    mkdir $LIBNET_DIR
    tar --strip=1 -xzvf $LIBNET_DIR.tar.gz -C $LIBNET_DIR 1>/dev/null
    cd $ROOT/$LIBNET_DIR/$LIBNET_DIR
    ./autogen.sh
    ./configure --prefix=$BUILD_DIR \
        --host=arm-linux-androideabi \
        --with-sysroot=$SYSROOT 1>/dev/null
    printf "\n[*]Compiling $LIBNET_DIR\n\n"
    make -j$(nproc)
    printf "\n[*]Installing $LIBNET_DIR\n\n"
    make install
fi
