#!/bin/bash

source ./env_setup

PROTOBUF_URL="https://github.com/google/protobuf/archive/v3.1.0.tar.gz"

PBUF_DIR="protobuf"

if [[ ! -d $PBUF_DIR ]]; then
    printf "\n[*]Downloading $PBUF_DIR\n\n"
    curl -L $PROTOBUF_URL > $PBUF_DIR.tar.gz
    mkdir $PBUF_DIR
    tar --strip=1 -xzvf $PBUF_DIR.tar.gz -C $PBUF_DIR 1>/dev/null
    cd $ROOT/$PBUF_DIR
    ./autogen.sh 1>/dev/null
    ./configure --prefix=$BUILD_DIR \
        --host=arm-linux-androideabi \
        --with-protoc=$X86_ROOT/bin/protoc \
        --disable-shared \
        --enable-static \
        LDFLAGS="-L${X86_ROOT}/lib -llog" 1>/dev/null
    printf "\n[*]Compiling $PBUF_DIR\n\n"
    make -j$(nproc)
    printf "\n[*]Installing $PBUF_DIR\n\n"
    make install
fi
