#!/bin/bash

export ROOT=`pwd`

PROTOBUF_URL="https://github.com/google/protobuf/archive/v3.3.0.tar.gz"

PBUF_DIR="protobuf"
PBUFC_DIR="protobuf-c"
CRIU_DIR="criu"
LIBNL_DIR="libnl"
LIBNET_DIR="libnet"
TARGET="arm"

export NDK_ROOT=$ROOT/cross
export BUILD_DIR=$ROOT/$TARGET
export SYSROOT=$NDK_ROOT/sysroot
export PATH=$NDK_ROOT/bin:$PATH
export CXX="arm-linux-androideabi-g++"
export CC="arm-linux-androideabi-gcc"

if [[ ! -d $PBUF_DIR ]]; then
    printf "\n[*]Downloading $PBUF_DIR\n\n"
    curl -L $PROTOBUF_URL > $PBUF_DIR.tar.gz
    mkdir $PBUF_DIR
    tar --strip=1 -xzvf $PBUF_DIR.tar.gz -C $PBUF_DIR 1>/dev/null
    cd $ROOT/$PBUF_DIR
    ./autogen.sh 1>/dev/null
    ./configure --prefix=$BUILD_DIR \
        --host=arm-linux-androideabi \
        --with-sysroot=$SYSROOT \
        --with-protoc=/usr/local/bin/protoc \
        --enable-cross-compile \
        LDFLAGS="-L/usr/local/lib -llog" 1>/dev/null
    printf "\n[*]Compiling $PBUF_DIR\n\n"
    make -j$(nproc)
    printf "\n[*]Installing $PBUF_DIR\n\n"
    make install
fi
